apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rtview-security-proxy.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rtview-security-proxy.name" . }}
    helm.sh/chart: {{ include "rtview-security-proxy.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  frontend.conf: |
      upstream rtview-dataserver {
          server {{ include "rtview-dataserver.fullname" . }}:3270;
      }

      server {
          listen       80;
          server_name  _;

          error_log /dev/stdout;
          access_log /dev/stdout;

          location / {
              proxy_pass http://rtview-dataserver/;
              proxy_set_header X-Forwarded-Host $host:$server_port;

              auth_basic "Restricted Area";
              auth_basic_user_file /etc/nginx/.htpasswd;

              expires off;
          }
      }
