#!/bin/bash

CWD=$(dirname "$0")

source "${CWD}/run-base.sh"

cp "${RTV_APP_ROOT}/collector/data.dat" "$PROJECT_DIR"

id_file_header="# AUTOGENERATED DURING FIRST LOAD COLLECTOR"
collector_properties_path="${RTV_APP_ROOT}/configs/collector.properties"

project_properties_path="${PROJECT_DIR}/project.properties"
if [ -z "$(cat "$project_properties_path" | grep "$id_file_header")" ]; then
  echo "$id_file_header" >> "$project_properties_path"
  cat "$collector_properties_path" >> "$project_properties_path"
fi

rundata.sh -propfilter:sender $RTV_CMD_ARGS -log4jprops:default.log4j.properties $*
