#!/bin/bash

PROJECT_DIR="/project"

cd ${RTV_RUNTIME_ROOT}/rtvapm && source ./rtvapm_init.sh

source fixperms.sh

rm -fr "${PROJECT_DIR}/lost+found"

if [ -z "$(ls -A ${PROJECT_DIR})" ]; then
  echo "Initialization of new project"

  cp -R "${RTV_RUNTIME_ROOT}/projects/rtview-server/." "${PROJECT_DIR}/"
else
  echo "Project already exists. Omitting"
fi

# Copy generic config definition
cp -n "${RTV_APP_ROOT}/configs/default.log4j.properties" "${PROJECT_DIR}" || true

id_file_header="# AUTOGENERATED DURING FIRST LOAD"
additional_properties_path="${RTV_APP_ROOT}/configs/additional.properties"

project_properties_path="${PROJECT_DIR}/project.properties"
if [ -z "$(cat "$project_properties_path" | grep "$id_file_header")" ]; then
  echo "$id_file_header" >> "$project_properties_path"
  cat "$additional_properties_path" >> "$project_properties_path"
fi

rtvapm_properties_path="${RTV_RUNTIME_ROOT}/rtvapm/common/conf/rtvapm.properties"
if [ -z "$(cat "$rtvapm_properties_path" | grep "$id_file_header")" ]; then
  echo "$id_file_header" >> "$rtvapm_properties_path"
  cat "$additional_properties_path" >> "$rtvapm_properties_path"
fi

cd "$PROJECT_DIR"

set -ex
