apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAACXBIWXMAAArrAAAK6wGCiw1aAAAFIGlUWHRYTUw6Y29tLmFkb2JlLnhtcAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4gPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgNS42LWMxNDAgNzkuMTYwNDUxLCAyMDE3LzA1LzA2LTAxOjA4OjIxICAgICAgICAiPiA8cmRmOlJERiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPiA8cmRmOkRlc2NyaXB0aW9uIHJkZjphYm91dD0iIiB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iIHhtbG5zOmRjPSJodHRwOi8vcHVybC5vcmcvZGMvZWxlbWVudHMvMS4xLyIgeG1sbnM6cGhvdG9zaG9wPSJodHRwOi8vbnMuYWRvYmUuY29tL3Bob3Rvc2hvcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RFdnQ9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZUV2ZW50IyIgeG1wOkNyZWF0b3JUb29sPSJBZG9iZSBQaG90b3Nob3AgQ0MgMjAxOCAoTWFjaW50b3NoKSIgeG1wOkNyZWF0ZURhdGU9IjIwMTgtMTAtMTZUMTM6MjY6NTErMDI6MDAiIHhtcDpNb2RpZnlEYXRlPSIyMDE4LTEwLTE2VDE0OjEzOjUzKzAyOjAwIiB4bXA6TWV0YWRhdGFEYXRlPSIyMDE4LTEwLTE2VDE0OjEzOjUzKzAyOjAwIiBkYzpmb3JtYXQ9ImltYWdlL3BuZyIgcGhvdG9zaG9wOkNvbG9yTW9kZT0iMyIgcGhvdG9zaG9wOklDQ1Byb2ZpbGU9InNSR0IgSUVDNjE5NjYtMi4xIiB4bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjk3NzdkMDYyLWFjMjgtNGQ0ZC1hZWJlLWY1ZmJiYzIwNzZlNCIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDo5Nzc3ZDA2Mi1hYzI4LTRkNGQtYWViZS1mNWZiYmMyMDc2ZTQiIHhtcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD0ieG1wLmRpZDo5Nzc3ZDA2Mi1hYzI4LTRkNGQtYWViZS1mNWZiYmMyMDc2ZTQiPiA8eG1wTU06SGlzdG9yeT4gPHJkZjpTZXE+IDxyZGY6bGkgc3RFdnQ6YWN0aW9uPSJjcmVhdGVkIiBzdEV2dDppbnN0YW5jZUlEPSJ4bXAuaWlkOjk3NzdkMDYyLWFjMjgtNGQ0ZC1hZWJlLWY1ZmJiYzIwNzZlNCIgc3RFdnQ6d2hlbj0iMjAxOC0xMC0xNlQxMzoyNjo1MSswMjowMCIgc3RFdnQ6c29mdHdhcmVBZ2VudD0iQWRvYmUgUGhvdG9zaG9wIENDIDIwMTggKE1hY2ludG9zaCkiLz4gPC9yZGY6U2VxPiA8L3htcE1NOkhpc3Rvcnk+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+PUDPpAAACUpJREFUeJztnU9y2soWh7+47jxkzCDcFYQ3QH54ks4KwmUDISsIqWL+8JyqS1YQsgFCVhB5AoUYPLKC4AHjK6/Ad9BH0BYSVksCZKyvSiUh9T/rpz7dfbolv7i/v6ekOFycugAlDykFKRilIAWjFKRglIIUjFKQglEKUjBKQQpGKUjBKAUpGKUgBePFqQtQNBaeVwdqQB2oyB459zoiyh2wBHzZLwG34Ti+Tb6BT/FZC7LwPIW+4cH2Jsfkb4EJMGw4zuqxwM9SEBGghb75b2OC+einHLZPfhwqtI/jBug3HMeNC/AsBFl4XgUtQAt9014al5fAiq2ZuW04zjJDXjW0yEryq0QEuwFaUebsrAVZeF4HfVPeG6ddY/tla+NTlOED0Ee3PSZ3gAqLf3aCSGPcRQvxEv30T9AC3BxagD3l+oQWpmKc3hHlLAQxTFIf3QNaoUX4lsX85I08LD/ZFaUWPChPWhCx112gA9yjRfhSJBHCxIjypeE4XXiigkgvqYtuG5bAEPhxKnNky8LzusDfodOvGo7jPylBRIg+uhczQpsk93QlSs/C837zsKH/2HCcUSDIH6coVFIMId6ghegkGWQVnC88rCV182IhBQkJMSSm7/5EcUO/6+aPQgkijXUf3UYMOS8hAGg4znLhebHXCyGIdF+7wCe0EH+emxAhVuwOGIECCCKj6j7wnfMXIuCWogki5mkE/IMeta5OVZYTUDOOffPCSQRZeF4f7YTb6wE9Y8x5Fde8cFRBZLQ6BL43HEcdM++iIJbBxDV/HE0QqRVvOY+xRBbqxrEfdvccXBCjrfjecJx3h87vCaCM4x/hiwcVRHpQHcpaYaKM42H44kEEkXHFEPj9XNuKKMRaBPP2yyjvdO6CSMPdR/egdjJ85nSM4y9RAXIVREyUQpsoP8+0z4SO7JcNxxlFBchNkIXntfZllIZqb6zkUBmnKzzsqbjG8RJYrQftZYq8Ojx8gvcxWg/aI5v05f4E44/PceEyC2JMo0baRBuqvXGL7TKdpGukdpbzVHvjO7RQE2CyHrT9BOm0otKKYZgwnElX9pN9g+FMghhiTNKaqGpvXEO3OS0eLtPJwku0x/g9MKz2xsP1oN1/JI6ySN+1KYxMJ7xFu0liawdkmDEMRpxpu7PV3riCftI+pC2DJb8AFVVbqr1xHfh/wnSW60H7PzYZLzzPRQvyueE4w6gwwYxhqsXW0pPyM4ih0C7oY4kB2gS68iCEqVukc2OTqVE7JnFimFgLsvC8SsNxlnEmajqbV/bFl8bzJ/mZJxveoM1jGGWRhmuZZx/98H1MEthakH1txXQ2r1w1L2OvS6P91TbPnOlE1BJlEd9NGlCGAW+Bv5K2sbm9H5KgZlTQPi1b7oBr4J1sX+RcWl5imCjpVES9ZhDFMmGPLejw9NGrSpZJC5fLOETEqF01L/dl3MXeTN2hG2IzXbfaG/fRHYKaZXoBZjxlEe+XRdg+MLIdl2UWJKEYkHzQZTKMGuTJU5omvSiURVg3SSDp9PxuOE6ke2QfmUxWUjGkW5nULJi0jNH6obBJ330sgJgqlUYMyFBDLGoG2HUrTd4AP6u98S3b9zhge2NW60F7lTJt2/YjaV410rWVQEpBLMWA9LY+4LVswfse/wsuVHvj4PAG4z2/9aA9SZCusijDo+OPYEhgkeYO1oKIGJ2r5uXQIppvm08KAj/Ue9gI9QPdDrkxcZRF+nFpbMjDw23VhgRiYF8lXcvwefEebfKGMdeVRVpu1sIkwbZR7wKTfYO/KKSnZOVyyJlP1d54ZJ44UPuRmcSCTGfzEbC8al6uUubVJduALisfxFMQoCziHu1hSiTIdDbvAqur5uUkbUZSS+rAt7Rp5EDHOFYW8dxcS7GHRwWZzuYt4MNV87KfNbP1oL1aD9od4BXa2bazDObAVIxjZRHPzbUUe9jby5rO5nV0A17PM1MZaY9kC9zxiu0XFdIMIhNT1PYD9ggiPaoRMMzQbiRCuqWueU5uWi0UtIIWrEM20eoWYY/aGdlXQ/poZ+AwTcLy1P9ME1e4XQ/atYjzE+nG/pMizYnslUUcN0U+e5nO5go9Ze2je63L4FpkGyIRPgHXtl3cHBkdIM2J7JVFHDfPAkibPJEy1ICJNA1AxJy6mKolcH/VvPwzbcbV3rjL7ivANkTOgYspm2D/5Z6b9aCtZF7GpnblZbL660Hbnc7mLvICK9p0dgHV/K/TgWiT1Ufb50RTjntYZoz/BlhVe2MznRrp246+7JVlvKRLgx7DDx1XZO+izRcQEmQ6m9fQpspnW71PyUvyuSHXhj9L5ZCeLb4xr+OiH44hWojgN7Dbhgxl/y1r2yE34JQj84BvoTVZ6gRl2Jg9Gc9N0Kaqhu7FjoLrmxoiDXng3nZzKsiE4y71CfNNBqLAZl4/z6/GJcU1f4go/aiAZg3pyt7P4iIJ0cVuHjov7oCPphiCOn5RAIsH/AI2bUdQO3IbCK0HbX89aNfRq0aOYb5uJa9azGJodYQyhPGj1gXEEZisrnEuceSkrAftvgzmWkR/bi8twRdBXfSi6uUj4VUOedpi9YC/AJjO5iu23cl3V81LN98y7WK4RpScqhP9ncIAV/arYDumj+nQbD7PJKNEc6HxqxOOzp8t5mLrlnmhFOO0XJCza70kGxc8dHHfnqgcJcIFDwdKB50YKnmck3+e6ZA8xX+auTMfIi6UkhNxge7Tm6jjFyMf7u/vH2xPkQt2fU2dE5SjRLhg1/H1WtZhPSnEH/fkeSFTtuEpzTtAWaxuPxnT2bwDcNW8HD1VM2US+LJG7M5bFFYUWSjQQvu+hoHv7ZwEqQC/2XXuFUYUQ4QW2vd2HXaCno0gsPmDv8eE+2z5PkhmpE1QPPzHLC4RQgSclSCwscdx75H/ArqHcs0bAgRb4DXw0VPB14+toDw7QWAjyt/Ez03cohdDuGlNmbj8a2jHpiJ6ec9K8km84OIsBYHN0/qVxweJwYzdit0BpkkdLXCN/f4yH/l3FGnEPltBAsSN8pXsL23uY4VMwV41LzO9nnD2ggSIifnE1rxkwWf739Ju8uzBPRtBTESct2zbAIg2bUv0zffZvmP+65CvNpyFIOfwR5wT5X+LLhilIAWjFKRglIIUjFKQglEKUjBKQQpGKUjBKAUpGKUgBaMUpGD8CzvoiUEjFBIdAAAAAElFTkSuQmCC
    marketplace.cloud.google.com/deploy-info: '{partner_id: "sl", product_id: "rtview-dataserver", partner_name: "SL Corporation"}'
  labels:
    app.kubernetes.io/name: {{ include "rtview.name" . }}
    helm.sh/chart: {{ include "rtview.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  descriptor:
    type: SL RTView Dataserver
    version: '4.2.0.0'
    description: >-
      SL RTView Dataserver app

    maintainers:
    - name: SL Corporation
      url: http://sl.com
    links:
    - description: 'RTView Enterprise Monitor® User’s Guide'
      url: http://sldownloads.sl.com/docs/RTViewEnterpriseMonitor_UserGuide_4.2.pdf
    notes: |-
      # Expose SL RTView Dataserver service

      By default, the application does not have an external IP. Run the
      following command to expose an external IP:

      ```
      kubectl patch service/{{ include "rtview-security-proxy.fullname" . }} \
        --namespace {{ .Release.Namespace }} \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

      # Access SL RTView Dataserver site

      Get the external IP of the RTView Dataserver site service and visit
      the URL printed below in your browser.

      ```
      SERVICE_IP=$(kubectl get service/{{ include "rtview-security-proxy.fullname" . }} \
        --namespace {{ .Release.Namespace }} \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}"
      ```

      Note that it might take some time for the external IP to be provisioned.
  info:
  - name: RTView Dataserver external IP
    type: Reference
    valueFrom:
      serviceRef:
        name: "{{ include "rtview-security-proxy.fullname" . }}"
  selector:
    matchLabels:
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  componentKinds:
  - group: apps/v1beta2
    kind: Deployment
  - group: extensions/v1beta1
    kind: Ingress
  - group: batch/v1
    kind: Job
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: v1
    kind: ConfigMap
