apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtview-dataserver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rtview-dataserver.name" . }}
    helm.sh/chart: {{ include "rtview-dataserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3270
      targetPort: dataserver
      protocol: TCP
      name: dataserver
    - port: 3272
      targetPort: ds-internal
      protocol: TCP
      name: ds-internal
    - port: 3275
      targetPort: ds-internal1
      protocol: TCP
      name: ds-internal1
    - port: 3276
      targetPort: ds-internal2
      protocol: TCP
      name: ds-internal2
    - port: 3278
      targetPort: ds-internal3
      protocol: TCP
      name: ds-internal3
  selector:
    app.kubernetes.io/name: {{ include "rtview-dataserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
